# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            robin Lee
tagline:          'A Jekyll theme'
description:      'robin Lee's Blog.'
url:              https://robinle.github.io
baseurl:          /

author:
  name:           'robin Lee'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde