# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

kramdown:
  input: GFM
  
# Setup
title:            robin Lee
tagline:          "robin Lee's Blog."
#description:      "robin Lee's Blog."
url:              https://robinle.github.io
baseurl:          /

author:
  name:           'robin Lee'
#  url:            https://twitter.com/mdo

gems: [jekyll-paginate]
paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde